"""Persisted PDF reports generated by chat and contract analysis."""

from __future__ import annotations

import enum
import uuid
from datetime import datetime

from sqlalchemy import BigInteger, DateTime, Enum, ForeignKey, Index, String, Text, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.db.base import Base


class GeneratedDocumentKind(str, enum.Enum):
    CHAT_REPORT = "chat_report"
    ANALYSIS_EXPORT = "analysis_export"


class GeneratedDocument(Base):
    """Metadata for one owner-scoped generated PDF stored on disk."""

    __tablename__ = "generated_documents"
    __table_args__ = (
        Index(
            "ix_generated_documents_user_created",
            "user_id",
            "created_at",
        ),
        Index(
            "ix_generated_documents_user_source_created",
            "user_id",
            "source_document_id",
            "created_at",
        ),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
    )
    source_document_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("documents.id", ondelete="SET NULL"),
        nullable=True,
    )
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    original_filename: Mapped[str] = mapped_column(String(255), nullable=False)
    stored_filename: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
        unique=True,
    )
    file_path: Mapped[str] = mapped_column(String(512), nullable=False)
    file_size: Mapped[int] = mapped_column(BigInteger, nullable=False)
    mime_type: Mapped[str] = mapped_column(
        String(100),
        nullable=False,
        default="application/pdf",
        server_default="application/pdf",
    )
    kind: Mapped[GeneratedDocumentKind] = mapped_column(
        Enum(
            GeneratedDocumentKind,
            name="generated_document_kind",
            values_callable=lambda enum_cls: [item.value for item in enum_cls],
        ),
        nullable=False,
        default=GeneratedDocumentKind.CHAT_REPORT,
        server_default=GeneratedDocumentKind.CHAT_REPORT.value,
    )
    question: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )


__all__ = ["GeneratedDocument", "GeneratedDocumentKind"]
