"""Persist, list and remove PDFs generated by the application."""

from __future__ import annotations

import asyncio
import re
from pathlib import Path
from uuid import UUID, uuid4

import aiofiles
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.config import Settings, get_settings
from app.core.exceptions import NotFoundError
from app.models.generated_document import GeneratedDocument, GeneratedDocumentKind
from app.repositories.document import DocumentRepository
from app.repositories.generated_document import GeneratedDocumentRepository


def _safe_pdf_name(value: str | None) -> str:
    base = (value or "rapport-genere").strip()
    if base.lower().endswith(".pdf"):
        base = base[:-4]
    base = re.sub(r"[^A-Za-z0-9À-ÿ._ -]+", "_", base).strip(" .")
    return f"{(base or 'rapport-genere')[:180]}.pdf"


class GeneratedDocumentService:
    def __init__(
        self,
        session: AsyncSession,
        settings: Settings | None = None,
    ) -> None:
        self._session = session
        self._repo = GeneratedDocumentRepository(session)
        self._documents = DocumentRepository(session)
        self._root = Path(
            (settings or get_settings()).generated_storage_path
        )

    async def save_pdf(
        self,
        content: bytes,
        *,
        user_id: UUID,
        source_document_id: UUID | None,
        title: str | None,
        filename: str | None,
        kind: GeneratedDocumentKind,
        question: str | None = None,
    ) -> GeneratedDocument:
        if source_document_id is not None:
            source = await self._documents.get_by_id(
                source_document_id,
                user_id=user_id,
            )
            if source is None:
                raise NotFoundError("Le contrat associé est introuvable.")

        original_filename = _safe_pdf_name(filename or title)
        clean_title = (title or original_filename[:-4]).strip()[:255]
        stored_filename = f"{uuid4()}.pdf"
        self._root.mkdir(parents=True, exist_ok=True)
        path = self._root / stored_filename
        async with aiofiles.open(path, "wb") as handle:
            await handle.write(content)

        item = GeneratedDocument(
            user_id=user_id,
            source_document_id=source_document_id,
            title=clean_title or "Rapport généré",
            original_filename=original_filename,
            stored_filename=stored_filename,
            file_path=str(path),
            file_size=len(content),
            mime_type="application/pdf",
            kind=kind,
            question=(question or "").strip() or None,
        )
        try:
            await self._repo.create(item)
            await self._session.commit()
            await self._session.refresh(item)
        except Exception:
            await self._session.rollback()
            await asyncio.to_thread(path.unlink, missing_ok=True)
            raise
        return item

    async def list_documents(
        self,
        *,
        user_id: UUID,
        source_document_id: UUID | None = None,
        skip: int = 0,
        limit: int = 100,
    ) -> tuple[list[tuple[GeneratedDocument, str | None]], int]:
        if source_document_id is not None:
            source = await self._documents.get_by_id(
                source_document_id,
                user_id=user_id,
            )
            if source is None:
                raise NotFoundError("Ce contrat est introuvable.")
        return await self._repo.list_all(
            user_id=user_id,
            source_document_id=source_document_id,
            skip=skip,
            limit=limit,
        )

    async def get_document(
        self,
        item_id: UUID,
        *,
        user_id: UUID,
    ) -> GeneratedDocument:
        item = await self._repo.get_by_id(item_id, user_id=user_id)
        if item is None:
            raise NotFoundError("Ce document généré est introuvable.")
        if not Path(item.file_path).is_file():
            raise NotFoundError("Le fichier PDF associé est introuvable.")
        return item

    async def delete_document(self, item_id: UUID, *, user_id: UUID) -> None:
        item = await self._repo.get_by_id(item_id, user_id=user_id)
        if item is None:
            raise NotFoundError("Ce document généré est introuvable.")
        path = Path(item.file_path)
        await self._repo.delete(item)
        await self._session.commit()
        await asyncio.to_thread(path.unlink, missing_ok=True)


__all__ = ["GeneratedDocumentService"]
