"""Private library of PDFs generated by chat and analysis."""

from uuid import UUID

from fastapi import APIRouter, Depends, Query, status
from fastapi.responses import FileResponse, Response
from sqlalchemy.ext.asyncio import AsyncSession

from app.api.deps import get_current_user
from app.db.session import get_db
from app.models.user import User
from app.schemas.generated_document import (
    GeneratedDocumentListResponse,
    GeneratedDocumentResponse,
)
from app.services.generated_document import GeneratedDocumentService

router = APIRouter(
    prefix="/generated-documents",
    tags=["Generated documents"],
)


def get_service(
    db: AsyncSession = Depends(get_db),
) -> GeneratedDocumentService:
    return GeneratedDocumentService(db)


@router.get("", response_model=GeneratedDocumentListResponse)
async def list_generated_documents(
    source_document_id: UUID | None = Query(default=None),
    skip: int = Query(0, ge=0),
    limit: int = Query(100, ge=1, le=500),
    service: GeneratedDocumentService = Depends(get_service),
    current_user: User = Depends(get_current_user),
) -> GeneratedDocumentListResponse:
    rows, total = await service.list_documents(
        user_id=current_user.id,
        source_document_id=source_document_id,
        skip=skip,
        limit=limit,
    )
    return GeneratedDocumentListResponse(
        items=[
            GeneratedDocumentResponse.model_validate(item).model_copy(
                update={"source_document_filename": source_filename}
            )
            for item, source_filename in rows
        ],
        total=total,
    )


@router.get("/{item_id}/file")
async def get_generated_document_file(
    item_id: UUID,
    download: bool = Query(default=False),
    service: GeneratedDocumentService = Depends(get_service),
    current_user: User = Depends(get_current_user),
) -> FileResponse:
    item = await service.get_document(item_id, user_id=current_user.id)
    disposition = "attachment" if download else "inline"
    return FileResponse(
        item.file_path,
        media_type="application/pdf",
        filename=item.original_filename,
        content_disposition_type=disposition,
    )


@router.delete("/{item_id}", status_code=status.HTTP_204_NO_CONTENT)
async def delete_generated_document(
    item_id: UUID,
    service: GeneratedDocumentService = Depends(get_service),
    current_user: User = Depends(get_current_user),
) -> Response:
    await service.delete_document(item_id, user_id=current_user.id)
    return Response(status_code=status.HTTP_204_NO_CONTENT)


__all__ = ["router"]
